### ISSUE TITLE
Error while compile

### ISSUE THREAD

**Issue by ketut** [BrookJeynes/zig-fetch#1]
src\main.zig:42:71: error: root struct of file 'http.Client' has no member named 'FetchResult'
    pub fn get(self: *Self, url: []const u8, headers: Headers) !Client.FetchResult {
                                                                ~~~~~~^~~~~~~~~~~~

**Comment by BrookJeynes** [comment]
Hey @ketut, what version of Zig are you using? 

I've just gone ahead and updated the repo to support Zig `version 0.12.0-dev.3318+6724a524d` - https://github.com/BrookJeynes/zig-fetch/commit/992ceaf554bc51d08ea5f569bee53f9d7fc26754

**Comment by ketut** [comment]
I use 0.11.0, 
I'm on 0.12.0-dev.3318+6724a524d and updated now, successfully compiled n run
Thank you @BrookJeynes
